//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.26 at 10:37:30 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.bharatthippireddy.com/Patient", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bharatthippireddy.patient;
