package server.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2015-07-26T16:56:26.693-04:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://soap.server/", name = "CustomerOrdersPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CustomerOrdersPortType {

    @WebResult(name = "createOrdersResponse", targetNamespace = "http://soap.server/", partName = "parameters")
    @WebMethod
    public CreateOrdersResponse createOrders(
        @WebParam(partName = "parameters", name = "createOrdersRequest", targetNamespace = "http://soap.server/")
        CreateOrdersRequest parameters
    );

    @WebResult(name = "getOrdersResponse", targetNamespace = "http://soap.server/", partName = "parameters")
    @WebMethod
    public GetOrdersResponse getOrders(
        @WebParam(partName = "parameters", name = "getOrdersRequest", targetNamespace = "http://soap.server/")
        GetOrdersRequest parameters
    );
}
